export const TOWNS_2: string[] = [
  "Newark, NJ",
  "Jersey City, NJ",
  "Paterson, NJ",
  "Elizabeth, NJ",
  "Lakewood Township, NJ",
  "Edison, NJ",
  "Woodbridge Township, NJ",
  "Toms River, NJ",
  "Hamilton Township, NJ",
  "Trenton, NJ",
  "Clifton, NJ",
  "Cherry Hill Township, NJ",
  "Brick Township, NJ",
  "Camden, NJ",
  "Bayonne, NJ",
  "Passaic, NJ",
  "East Orange, NJ",
  "Union City, NJ",
  "Franklin Township, NJ",
  "Middletown, NJ",
  "Old Bridge Township, NJ",
  "Gloucester Township, NJ",
  "North Bergen, NJ",
  "Irvington, NJ",
  "Piscataway, NJ",
  "Vineland, NJ",
  "Hoboken, NJ",
  "Union, NJ",
  "Jackson Township, NJ",
  "Parsippany-Troy Hills, NJ",
  "Perth Amboy, NJ",
  "New Brunswick, NJ",
  "Wayne, NJ",
  "Plainfield, NJ",
  "Howell, NJ",
  "Bloomfield, NJ",
  "West New York, NJ",
  "East Brunswick, NJ",
  "West Orange, NJ",
  "Washington Township, NJ",
  "Monroe Township, NJ",
  "Egg Harbor Township, NJ",
  "South Brunswick, NJ",
  "Evesham, NJ",
  "Hackensack, NJ",
  "Bridgewater Township, NJ",
  "Sayreville, NJ",
  "Manchester Township, NJ",
  "Mount Laurel, NJ",
  "North Brunswick, NJ",
  "Berkeley Township, NJ",
  "Linden, NJ",
  "Hillsborough Township, NJ",
  "Kearny, NJ",
  "Marlboro, NJ",
  "Teaneck, NJ",
  "Montclair, NJ",
  "Manalapan, NJ",
  "Fort Lee, NJ",
  "Winslow Township, NJ",
  "Atlantic City, NJ",
  "Belleville, NJ",
  "Galloway, NJ",
  "Ewing Township, NJ",
  "Monroe Township, NJ",
  "Pennsauken, NJ",
  "Freehold Township, NJ",
  "Fair Lawn, NJ",
  "Orange, NJ",
  "Lawrence Township, NJ",
  "Garfield, NJ",
  "Deptford, NJ",
  "Willingboro, NJ",
  "Long Branch, NJ",
  "Livingston, NJ",
  "Voorhees, NJ",
  "Westfield, NJ",
  "Princeton, NJ",
  "Nutley, NJ",
  "East Windsor, NJ",
  "Rahway, NJ",
  "West Windsor, NJ",
  "Englewood, NJ",
  "Mount Olive, NJ",
  "Lacey Township, NJ",
  "Stafford Township, NJ",
  "Bergenfield, NJ",
  "Neptune Township, NJ",
  "Bernards Township, NJ",
  "Ocean Township, NJ",
  "Millville, NJ",
  "Hamilton Township, NJ",
  "Bridgeton, NJ",
  "Pemberton Township, NJ",
  "Paramus, NJ",
  "Wall, NJ",
  "Randolph, NJ",
  "Lodi, NJ",
  "Ridgewood, NJ",
  "Cliffside Park, NJ",
  "Maplewood, NJ",
  "Mahwah, NJ",
  "Rockaway Township, NJ",
  "Carteret, NJ",
  "Scotch Plains, NJ",
  "West Milford, NJ",
  "Medford, NJ",
  "South Plainfield, NJ",
  "Barnegat Township, NJ",
  "Plainsboro Township, NJ",
  "Burlington Township, NJ",
  "Cranford, NJ",
  "Montgomery Township, NJ",
  "Raritan Township, NJ",
  "Glassboro, NJ",
  "Morris Township, NJ",
  "Roxbury, NJ",
  "North Plainfield, NJ",
  "Summit, NJ",
  "Roselle, NJ",
  "Lyndhurst, NJ",
  "Hillside, NJ",
  "Montville, NJ",
  "Vernon Township, NJ",
  "West Deptford, NJ",
  "Secaucus, NJ",
  "Lower Township, NJ",
  "Millburn, NJ",
  "Lindenwold, NJ",
  "Elmwood Park, NJ",
  "Moorestown, NJ",
  "Little Egg Harbor Township, NJ",
  "Pleasantville, NJ",
  "Jefferson, NJ",
  "Middle Township, NJ",
  "Palisades Park, NJ",
  "Morristown, NJ",
  "Hazlet, NJ",
  "Maple Shade, NJ",
  "Hawthorne, NJ",
  "Sparta, NJ",
  "Harrison, NJ",
  "Aberdeen, NJ",
  "Tinton Falls, NJ",
  "Point Pleasant, NJ",
  "Rutherford, NJ",
  "South Orange, NJ",
  "Dover, NJ",
  "Washington Township, NJ",
  "Delran Township, NJ",
  "Dumont, NJ",
  "Hopewell Township, NJ",
  "Holmdel, NJ",
  "Weehawken, NJ",
  "Springfield, NJ",
  "Denville, NJ",
  "Cinnaminson, NJ",
  "Madison, NJ",
  "New Milford, NJ",
  "Wyckoff, NJ",
  "North Arlington, NJ",
  "Franklin Township, NJ",
  "Readington Township, NJ",
  "South River, NJ",
  "Warren Township, NJ",
  "Pequannock, NJ",
  "Clark, NJ",
  "Robbinsville Township, NJ",
  "Tenafly, NJ",
  "Haddon Township, NJ",
  "Phillipsburg, NJ",
  "Mantua Township, NJ",
  "Asbury Park, NJ",
  "Highland Park, NJ",
  "Metuchen, NJ",
  "Fairview, NJ",
  "Branchburg, NJ",
  "Ramsey, NJ",
  "Hammonton, NJ",
  "Hanover, NJ",
  "Middlesex, NJ",
  "Verona, NJ",
  "Hopatcong, NJ",
  "Edgewater, NJ",
  "Saddle Brook, NJ",
  "Collingswood, NJ",
  "Roselle Park, NJ",
  "New Providence, NJ",
  "Harrison Township, NJ",
  "Eatontown, NJ",
  "Clinton Township, NJ",
  "Woodland Park, NJ",
  "Little Falls, NJ",
  "Berkeley Heights, NJ",
  "Ridgefield Park, NJ",
  "Cedar Grove, NJ",
  "Red Bank, NJ",
  "Florence Township, NJ",
  "Lumberton, NJ",
  "Oakland, NJ",
  "Pennsville Township, NJ",
  "Florham Park, NJ",
  "Woolwich Township, NJ",
  "Haddonfield, NJ",
  "Upper Township, NJ",
  "Freehold Borough, NJ",
  "Somerville, NJ",
  "Glen Rock, NJ",
  "Hasbrouck Heights, NJ",
  "River Edge, NJ",
  "Guttenberg, NJ",
  "Bound Brook, NJ",
  "Wallington, NJ",
  "Bordentown Township, NJ",
  "Ringwood, NJ",
  "Bellmawr, NJ",
  "East Greenwich Township, NJ",
  "Ridgefield, NJ",
  "Gloucester City, NJ",
  "Wanaque, NJ",
  "Westwood, NJ",
  "Ocean City, NJ",
  "Pompton Lakes, NJ",
  "East Hanover, NJ",
  "Franklin Lakes, NJ",
  "Totowa, NJ",
  "West Caldwell, NJ",
  "Little Ferry, NJ",
  "Chatham Township, NJ",
  "Manville, NJ",
  "Lincoln Park, NJ",
  "Beachwood, NJ",
  "Wantage Township, NJ",
  "Pine Hill, NJ",
  "Somers Point, NJ",
  "Waterford Township, NJ",
  "Millstone Township, NJ",
  "Southampton, NJ",
  "Hackettstown, NJ",
  "Hillsdale, NJ",
  "Wood-Ridge, NJ",
  "Maywood, NJ",
  "Waldwick, NJ",
  "East Rutherford, NJ",
  "Mount Holly, NJ",
  "Kinnelon, NJ",
  "Woodbury, NJ",
  "Colts Neck, NJ",
  "River Vale, NJ",
  "Keansburg, NJ",
  "Burlington City, NJ",
  "Matawan, NJ",
  "Chesterfield, NJ",
  "South Amboy, NJ",
  "Leonia, NJ",
  "Washington Township, NJ",
  "Chatham Borough, NJ",
  "Ventnor City, NJ",
  "Cresskill, NJ",
  "Absecon, NJ",
  "Westampton, NJ",
  "Haledon, NJ",
  "Caldwell, NJ",
  "Edgewater Park, NJ",
  "North Haledon, NJ",
  "Mansfield Township, NJ",
  "Park Ridge, NJ",
  "Ocean Township, NJ",
  "Boonton Town, NJ",
  "Clayton, NJ",
  "Pitman, NJ",
  "Bogota, NJ",
  "Pittsgrove, NJ",
  "Lopatcong, NJ",
  "Audubon, NJ",
  "Carneys Point, NJ",
  "Long Hill, NJ",
  "Closter, NJ",
  "West Long Branch, NJ",
  "Montvale, NJ",
  "Northfield, NJ",
  "Kenilworth, NJ",
  "Newton, NJ",
  "Upper Saddle River, NJ",
  "Runnemede, NJ",
  "Bedminster, NJ",
  "Oradell, NJ",
  "Spotswood, NJ",
  "Hardyston, NJ",
  "Plumsted, NJ",
  "Butler, NJ",
  "Byram Township, NJ",
  "Riverside, NJ",
  "North Hanover Township, NJ",
  "Bernardsville, NJ",
  "Fairfield, NJ",
  "Raritan, NJ",
  "Glen Ridge, NJ",
  "Mansfield Township, NJ",
  "Bloomingdale, NJ",
  "Fanwood, NJ",
  "Brigantine, NJ",
  "Chester Township, NJ",
  "Upper Deerfield Township, NJ",
  "Dunellen, NJ",
  "Haddon Heights, NJ",
  "Berlin Borough, NJ",
  "Palmyra, NJ",
  "Rumson, NJ",
  "Washington Borough, NJ",
  "Emerson, NJ",
  "Green Brook Township, NJ",
  "Upper Freehold, NJ",
  "Wharton, NJ",
  "Keyport, NJ",
  "Barrington, NJ",
  "Milltown, NJ",
  "Buena Vista Township, NJ",
  "Mountainside, NJ",
  "Midland Park, NJ",
  "Stratford, NJ",
  "Linwood, NJ",
  "Allendale, NJ",
  "Tabernacle, NJ",
  "North Caldwell, NJ",
  "Rockaway Borough, NJ",
  "Union Township, NJ",
  "Washington Township, NJ",
  "Shamong, NJ",
  "Watchung, NJ",
  "Carlstadt, NJ",
  "Prospect Park, NJ",
  "New Hanover Township, NJ",
  "Roseland, NJ",
  "Dennis Township, NJ",
  "Fair Haven, NJ",
  "Maurice River Township, NJ",
  "Paulsboro, NJ",
  "Lebanon Township, NJ",
  "Eastampton, NJ",
  "Morris Plains, NJ",
  "Oceanport, NJ",
  "Little Silver, NJ",
  "Woodcliff Lake, NJ",
  "Hainesport, NJ",
  "Mendham Township, NJ",
  "Logan Township, NJ",
  "Andover Township, NJ",
  "Manasquan, NJ",
  "Mount Arlington, NJ",
  "Belmar, NJ",
  "Hightstown, NJ",
  "Old Tappan, NJ",
  "Tewksbury, NJ",
  "Berlin Township, NJ",
  "Mullica Township, NJ",
  "Rochelle Park, NJ",
  "Jamesburg, NJ",
  "Union Beach, NJ",
  "Blairstown, NJ",
  "Norwood, NJ",
  "Somerdale, NJ",
  "Fairfield Township, NJ",
  "Greenwich Township, NJ",
  "Independence Township, NJ",
  "Englewood Cliffs, NJ",
  "Clementon, NJ",
  "Allamuchy Township, NJ",
  "Margate City, NJ",
  "Frankford, NJ",
  "Salem, NJ",
  "Holland Township, NJ",
  "Wildwood, NJ",
  "Brielle, NJ",
  "Demarest, NJ",
  "Mendham Borough, NJ",
  "Greenwich Township, NJ",
  "Franklin Borough, NJ",
  "Hampton Township, NJ",
  "Spring Lake Heights, NJ",
  "Flemington, NJ",
  "South Bound Brook, NJ",
  "Penns Grove, NJ",
  "Delanco, NJ",
  "Alexandria, NJ",
  "Point Pleasant Beach, NJ",
  "Northvale, NJ",
  "Harrington Park, NJ",
  "Commercial Township, NJ",
  "Mount Ephraim, NJ",
  "Neptune City, NJ",
  "Highlands, NJ",
  "White, NJ",
  "Delaware Township, NJ",
  "Buena, NJ",
  "Mountain Lakes, NJ",
  "Garwood, NJ",
  "Elk Township, NJ",
  "Atlantic Highlands, NJ",
  "Egg Harbor City, NJ",
  "Hopewell Township, NJ",
  "Boonton Township, NJ",
  "Magnolia, NJ",
  "Bradley Beach, NJ",
  "Medford Lakes, NJ",
  "Westville, NJ",
  "Ho-Ho-Kus, NJ",
  "Shrewsbury Borough, NJ",
  "Pilesgrove, NJ",
  "Lambertville, NJ",
  "Riverdale, NJ",
  "Mine Hill, NJ",
  "Stillwater Township, NJ",
  "Bordentown City, NJ",
  "Oaklyn, NJ",
  "East Amwell Township, NJ",
  "Harding, NJ",
  "Cranbury, NJ",
  "Merchantville, NJ",
  "Kingwood, NJ",
  "Montague, NJ",
  "Bethlehem Township, NJ",
  "Woodstown, NJ",
  "South Toms River, NJ",
  "Green Township, NJ",
  "North Wildwood, NJ",
  "Tuckerton, NJ",
  "High Bridge, NJ",
  "Stanhope, NJ",
  "Upper Pittsgrove, NJ",
  "South Harrison Township, NJ",
  "Netcong, NJ",
  "Saddle River, NJ",
  "Haworth, NJ",
  "Alloway Township, NJ",
  "Franklin Township, NJ",
  "Hamburg, NJ",
  "Springfield, NJ",
  "Pohatcong, NJ",
  "Fredon Township, NJ",
  "Monmouth Beach, NJ",
  "Long Beach Township, NJ",
  "Deerfield Township, NJ",
  "Moonachie, NJ",
  "Wildwood Crest, NJ",
  "Woodbury Heights, NJ",
  "Lawrence Township, NJ",
  "National Park, NJ",
  "West Amwell Township, NJ",
  "Franklin Township, NJ",
  "Lawnside, NJ",
  "Woodlynne, NJ",
  "Knowlton Township, NJ",
  "Pennington, NJ",
  "Spring Lake, NJ",
  "Clinton Town, NJ",
  "Cape May, NJ",
  "Riverton, NJ",
  "Swedesboro, NJ",
  "South Hackensack, NJ",
  "Liberty, NJ",
  "Lakehurst, NJ",
  "Weymouth Township, NJ",
  "East Newark, NJ",
  "Quinton Township, NJ",
  "Peapack and Gladstone, NJ",
  "Belvidere, NJ",
  "Harmony Township, NJ",
  "Beverly, NJ",
  "Helmetta, NJ",
  "Oxford Township, NJ",
  "Seaside Heights, NJ",
  "Lafayette Township, NJ",
  "Englishtown, NJ",
  "Alpha, NJ",
  "Wenonah, NJ",
  "Ogdensburg, NJ",
  "Essex Fells, NJ",
  "Frelinghuysen Township, NJ",
  "Gibbsboro, NJ",
  "Pine Beach, NJ",
  "Woodbine, NJ",
  "Sea Isle City, NJ",
  "Sussex, NJ",
  "Laurel Springs, NJ",
  "Sandyston, NJ",
  "Avon-by-the-Sea, NJ",
  "Ocean Gate, NJ",
  "Hopewell Borough, NJ",
  "Oldmans Township, NJ",
  "Sea Girt, NJ",
  "Hope Township, NJ",
  "Brooklawn, NJ",
  "Folsom, NJ",
  "Lavallette, NJ",
  "Newfield, NJ",
  "Alpine, NJ",
  "Allentown, NJ",
  "Eagleswood Township, NJ",
  "Lower Alloways Creek, NJ",
  "Lake Como, NJ",
  "Glen Gardner, NJ",
  "Chester Borough, NJ",
  "Estell Manor, NJ",
  "Lebanon Borough, NJ",
  "Island Heights, NJ",
  "Hardwick Township, NJ",
  "Victory Gardens, NJ",
  "Woodland Township, NJ",
  "Chesilhurst, NJ",
  "Farmingdale, NJ",
  "Mannington Township, NJ",
  "Sea Bright, NJ",
  "Hampton Borough, NJ",
  "Seaside Park, NJ",
  "Winfield, NJ",
  "Downe Township, NJ",
  "Pemberton Borough, NJ",
  "Frenchtown, NJ",
  "Bass River Township, NJ",
  "Elmer, NJ",
  "Stow Creek Township, NJ",
  "Avalon, NJ",
  "Surf City, NJ",
  "Milford, NJ",
  "Port Republic, NJ",
  "Ship Bottom, NJ",
  "Shrewsbury Township, NJ",
  "Beach Haven, NJ",
  "West Cape May, NJ",
  "Califon, NJ",
  "Elsinboro, NJ",
  "Audubon Park, NJ",
  "Bay Head, NJ",
  "Hi-Nella, NJ",
  "Far Hills, NJ",
  "Deal, NJ",
  "Longport, NJ",
  "Interlaken, NJ",
  "Roosevelt, NJ",
  "Stone Harbor, NJ",
  "Bloomsbury, NJ",
  "Branchville, NJ",
  "Greenwich Township, NJ",
  "Rocky Hill, NJ",
  "Wrightstown, NJ",
  "Washington Township, NJ",
  "Barnegat Light, NJ",
  "Andover Borough, NJ",
  "West Wildwood, NJ",
  "Fieldsboro, NJ",
  "Stockton, NJ",
  "Allenhurst, NJ",
  "Corbin City, NJ",
  "Millstone Borough, NJ",
  "Shiloh, NJ",
  "Rockleigh, NJ",
  "Harvey Cedars, NJ",
  "Mantoloking, NJ",
  "Cape May Point, NJ",
  "Loch Arbour, NJ",
  "Teterboro, NJ",
  "Tavistock, NJ",
  "Walpack Township, NJ",
];

export const TOWNS: Record<string, {place_id: string; real_name: string; display_name: string}> = {
  "Paterson-NJ": { place_id: "ChIJgUIFaTT8wokR2iT7x2DRyr4", real_name: "Paterson, NJ, USA", display_name: "Paterson, NJ" },
  "Clifton-NJ": { place_id: "ChIJ6drDvuL-wokRUzJ_IjNYGWQ", real_name: "Clifton, NJ, USA", display_name: "Clifton, NJ" },
  "Wayne-NJ": { place_id: "ChIJ04Q8EWACw4kRRAOyHJpTVOY", real_name: "Wayne, NJ, USA", display_name: "Wayne, NJ" },
  "Hawthorne-NJ": { place_id: "ChIJ_fej-ML8wokRDV16Ol_Md_o", real_name: "Hawthorne, NJ 07506, USA", display_name: "Hawthorne, NJ" },
  "LittleFalls-NJ": { place_id: "ChIJG5Rsv9YBw4kRbSAGfIdVtQ4", real_name: "Little Falls Township, NJ, USA", display_name: "Little Falls, NJ" },
  "Montclair-NJ": { place_id: "ChIJoSOnRlZVwokRFLIX0GYzn0Q", real_name: "Montclair, NJ, USA", display_name: "Montclair, NJ" },
  "Totowa-NJ": { place_id: "ChIJg84swf4Bw4kRDxGX6YY9B9U", real_name: "Totowa, NJ, USA", display_name: "Totowa, NJ" },
  "NorthHaledon-NJ": { place_id: "ChIJkYFvhT39wokRP27clUKeexc", real_name: "North Haledon, NJ, USA", display_name: "North Haledon, NJ" },
  "Wanaque-NJ": { place_id: "ChIJ6asP5hgcw4kRFvjZQQvCTPQ", real_name: "Wanaque, NJ, USA", display_name: "Wanaque, NJ" },
  "Passaic-NJ": { place_id: "ChIJm0rHLNT-wokRgywG2zgBKoE", real_name: "Passaic, NJ, USA", display_name: "Passaic, NJ" },
  "Hackensack-NJ": { place_id: "ChIJSd7vtxv6wokR1xbdaIitCkI", real_name: "Hackensack, NJ, USA", display_name: "Hackensack, NJ" },
  "Paramus-NJ": { place_id: "ChIJw13uaeD6wokRWdp8YYjKDfI", real_name: "Paramus, NJ 07652, USA", display_name: "Paramus, NJ" },
  "Englewood-NJ": { place_id: "ChIJjXk9hxjxwokRvpsfnmiaxsQ", real_name: "Englewood, NJ 07631, USA", display_name: "Englewood, NJ" },
  "Teaneck-NJ": { place_id: "ChIJd-L_HbrwwokRzzONycC4Qmc", real_name: "Teaneck, NJ, USA", display_name: "Teaneck, NJ" },
  "FortLee-NJ": { place_id: "ChIJUelm2Of2wokRRCV4_VtJdYU", real_name: "Fort Lee, NJ 07024, USA", display_name: "Fort Lee, NJ" },
  "Ridgewood-NJ": { place_id: "ChIJOYyoQ6XkwokRsJcmXQpaGAc", real_name: "Ridgewood, NJ 07450, USA", display_name: "Ridgewood, NJ" },
  "Bergenfield-NJ": { place_id: "ChIJg5dda07wwokReRwv_tzckVU", real_name: "Bergenfield, NJ, USA", display_name: "Bergenfield, NJ" },
  "FairLawn-NJ": { place_id: "ChIJrdI9S3n7wokRcV2_yHiZLqY", real_name: "Fair Lawn, NJ, USA", display_name: "Fair Lawn, NJ" },
  "LittleFerry-NJ": { place_id: "ChIJac2Pbsz5wokRnsgMAcTG6XQ", real_name: "Little Ferry, NJ 07643, USA", display_name: "Little Ferry, NJ" },
  "Newton-NJ": { place_id: "ChIJ5cCIrRhww4kRKqNF2ZxZY8k", real_name: "Newton, NJ, USA", display_name: "Newton, NJ" },
  "Vernon-NJ": { place_id: "ChIJ3T_CSe89w4kRwmWXMyJerS8", real_name: "Vernon Township, NJ, USA", display_name: "Vernon, NJ" },
  "Hopatcong-NJ": { place_id: "ChIJFUUVFbJxw4kRC0h7x2Y33LI", real_name: "Hopatcong, NJ, USA", display_name: "Hopatcong, NJ" },
  "Sparta-NJ": { place_id: "ChIJ2TgSZYRyw4kRvCYqmdE2joU", real_name: "Sparta, NJ 07871, USA", display_name: "Sparta, NJ" },
  "Wantage-NJ": { place_id: "ChIJR15DneRAw4kR0FHibfcYsI4", real_name: "Wantage, NJ, USA", display_name: "Wantage, NJ" },
  "Stillwater-NJ": { place_id: "ChIJs8BhftBkw4kRaqZwG4s9kYU", real_name: "Stillwater Township, NJ 07860, USA", display_name: "Stillwater, NJ" },
  "Hamburg-NJ": { place_id: "ChIJGboBQ94Uw4kRhEWxYeeCdWM", real_name: "Hamburg, NJ 07419, USA", display_name: "Hamburg, NJ" },
  "Stanhope-NJ": { place_id: "ChIJRV8V2eBww4kRlIKtvM3ZNAY", real_name: "Stanhope, NJ 07874, USA", display_name: "Stanhope, NJ" },
  "Franklin-NJ": { place_id: "ChIJMcM7g5Vrw4kRhs0cZhqMVA8", real_name: "Franklin, NJ, USA", display_name: "Franklin, NJ" },
  "Andover-NJ": { place_id: "ChIJqYStXq1xw4kRpv2mWPMf24I", real_name: "Andover Township, NJ, USA", display_name: "Andover, NJ" },
  "Newark-NJ": { place_id: "ChIJHQ6aMnBTwokRc-T-3CrcvOE", real_name: "Newark, NJ, USA", display_name: "Newark, NJ" },
  "EastOrange-NJ": { place_id: "ChIJw4KJlbVUwokREiZaBTE5q7Y", real_name: "East Orange, NJ, USA", display_name: "East Orange, NJ" },
  "Irvington-NJ": { place_id: "ChIJ0eTyM8Ssw4kRX1VaLtbAylA", real_name: "Irvington, NJ 07111, USA", display_name: "Irvington, NJ" },
  "Bloomfield-NJ": { place_id: "ChIJQdQJH2xVwokRoQYH--sARMM", real_name: "Bloomfield, NJ, USA", display_name: "Bloomfield, NJ" },
  "Belleville-NJ": { place_id: "ChIJ34Ftr6VVwokRtPc4B_j8W4Y", real_name: "Belleville, NJ, USA", display_name: "Belleville, NJ" },
  "WestOrange-NJ": { place_id: "ChIJVehe2ACrw4kR0J0mQLoVOgk", real_name: "West Orange, NJ 07052, USA", display_name: "West Orange, NJ" },      
  "SouthOrange-NJ": { place_id: "ChIJ9fVFqIasw4kRSWiIxIvoq9I", real_name: "South Orange Village, NJ 07079, USA", display_name: "South Orange, NJ" },
  "Nutley-NJ": { place_id: "ChIJqzIotmP_wokR7Qard6aizeA", real_name: "Nutley, NJ, USA", display_name: "Nutley, NJ" },
  "Maplewood-NJ": { place_id: "ChIJt-wTlmCsw4kR6SsoR_6D7L8", real_name: "Maplewood, NJ, USA", display_name: "Maplewood, NJ" },
  "Parsippany-TroyHills-NJ": { place_id: "ChIJwyhwKCQIw4kR8CRjsZCYpfY", real_name: "Parsippany-Troy Hills, NJ, USA", display_name: "Parsippany-Troy Hills, NJ" },
  "Morristown-NJ": { place_id: "ChIJLSKWIZMJw4kRoSFvsb55sEM", real_name: "Morristown, NJ 07960, USA", display_name: "Morristown, NJ" },        
  "MountOlive-NJ": { place_id: "ChIJlRu_z0Cdw4kRp6XlRu4qvBg", real_name: "Mt Olive, NJ, USA", display_name: "Mount Olive, NJ" },
  "Roxbury-NJ": { place_id: "ChIJx5fjlyiew4kRFsKJPTTCcVo", real_name: "Roxbury Township, NJ, USA", display_name: "Roxbury, NJ" },
  "Randolph-NJ": { place_id: "ChIJV2Gsmy6gw4kRjHgPq-mcaok", real_name: "Randolph, NJ, USA", display_name: "Randolph, NJ" },
  "Denville-NJ": { place_id: "ChIJd2WLyZQJw4kRka9dlQzEWy0", real_name: "Denville, NJ, USA", display_name: "Denville, NJ" },
  "Boonton-NJ": { place_id: "ChIJHYuTkScGw4kRjc-T9JIvE4Y", real_name: "Boonton, NJ 07005, USA", display_name: "Boonton, NJ" },
  "Jefferson-NJ": { place_id: "ChIJo1rEk6sNw4kRdCQnvUGZ4Us", real_name: "Jefferson, NJ, USA", display_name: "Jefferson, NJ" },
  "Parsippany-NJ": { place_id: "ChIJwyhwKCQIw4kR8CRjsZCYpfY", real_name: "Parsippany-Troy Hills, NJ, USA", display_name: "Parsippany, NJ" },   
  "MountainLakes-NJ": { place_id: "ChIJ98cxY1AIw4kRoEFAewtaGAc", real_name: "Mountain Lakes, NJ, USA", display_name: "Mountain Lakes, NJ" },   
  "Washington-NJ": { place_id: "ChIJCTnnNlF_w4kRL5poBO8YOY8", real_name: "Washington, NJ 07882, USA", display_name: "Washington, NJ" },        
  "Hackettstown-NJ": { place_id: "ChIJa2-_bAqDw4kRMhdg4epA_mw", real_name: "Hackettstown, NJ 07840, USA", display_name: "Hackettstown, NJ" },  
  "Phillipsburg-NJ": { place_id: "ChIJV0wCcaNtxIkR4o0oI1ZU6Q4", real_name: "Phillipsburg, NJ 08865, USA", display_name: "Phillipsburg, NJ" },  
  "Belvidere-NJ": { place_id: "ChIJT_PVSat4w4kRJOnrmPnUKHU", real_name: "Belvidere, NJ 07823, USA", display_name: "Belvidere, NJ" },
  "Oxford-NJ": { place_id: "ChIJh7jsDmd4xIkRHE28_sJHE7o", real_name: "Oxford, NJ 07863, USA", display_name: "Oxford, NJ" },
  "Lopatcong-NJ": { place_id: "ChIJPSfpCglyxIkR1Xkl6kTqutM", real_name: "Lopatcong, NJ, USA", display_name: "Lopatcong, NJ" },
  "White-NJ": { place_id: "ChIJRVqDKgp5xIkRqWbjBiXTVjE", real_name: "White, NJ, USA", display_name: "White, NJ" },
  "Warren-NJ": { place_id: "ChIJnZxrSgvAw4kREMSALDlYcys", real_name: "Warren, NJ, USA", display_name: "Warren, NJ" },
  "Allamuchy-NJ": { place_id: "ChIJp4uBAOV4w4kRz2vrVArfZjo", real_name: "Allamuchy Township, NJ, USA", display_name: "Allamuchy, NJ" },        
};