export enum Genre {
  ALTERNATIVE = "ALTERNATIVE",
  AMERICANA = "AMERICANA",
  BLUES = "BLUES",
  CLASSIC_ROCK = "CLASSIC_ROCK",
  COUNTRY = "COUNTRY",
  DANCE = "DANCE",
  DJ = "DJ",
  EDM = "EDM",
  FOLK = "FOLK",
  FUNK = "FUNK",
  HIP_HOP = "HIP_HOP",
  INDIE = "INDIE",
  JAM_BAND = "JAM_BAND",
  JAZZ = "JAZZ",
  KARAOKE = "KARAOKE",
  LATIN = "LATIN",
  METAL = "METAL",
  POP = "POP",
  RNB_SOUL = "RNB_SOUL",
  REGGAE = "REGGAE",
  ROCK = "ROCK",
  SINGER_SONGWRITER = "SINGER_SONGWRITER",
  WORLD_MUSIC = "WORLD_MUSIC",
}

export const GenreLabels: Record<Genre, string> = {
  [Genre.ALTERNATIVE]: "Alternative",
  [Genre.BLUES]: "Blues",
  [Genre.CLASSIC_ROCK]: "Classic Rock",
  [Genre.COUNTRY]: "Country",
  [Genre.DANCE]: "Dance",
  [Genre.DJ]: "DJ",
  [Genre.EDM]: "EDM",
  [Genre.FOLK]: "Folk",
  [Genre.HIP_HOP]: "Hip Hop",
  [Genre.INDIE]: "Indie",
  [Genre.JAZZ]: "Jazz",
  [Genre.KARAOKE]: "Karaoke",
  [Genre.LATIN]: "Latin",
  [Genre.METAL]: "Metal",
  [Genre.POP]: "Pop",
  [Genre.RNB_SOUL]: "R'n'B Soul",
  [Genre.REGGAE]: "Reggae",
  [Genre.ROCK]: "Rock",
  [Genre.WORLD_MUSIC]: "World Music",
  [Genre.JAM_BAND]: "Jam Band",
  [Genre.FUNK]: "Funk",
  [Genre.AMERICANA]: "Americana",
  [Genre.SINGER_SONGWRITER]: "Singer-Songwriter",
};
